export const SECONDS_IN_A_MINUTE = 60
export const SECONDS_IN_AN_HOUR = 60 * SECONDS_IN_A_MINUTE
export const SECONDS_IN_A_DAY = 24 * SECONDS_IN_AN_HOUR
export const SECONDS_IN_A_MONTH = 30 * SECONDS_IN_A_DAY
export const SECONDS_IN_A_YEAR = 365 * SECONDS_IN_A_DAY
